#!/usr/bin/env python3
"""Pin requirements.txt to the versions installed in the current environment.

Run this inside the environment that produced the paper's results:

    python pin_requirements.py --code-dir ../path/to/experiment-code

It writes requirements.lock.txt with an exact ``name==version`` line for every
package listed in requirements.txt, and reports:

  * listed packages that are not installed (remove them, or install and re-run);
  * third-party packages imported by the code under --code-dir that are not
    listed in requirements.txt (add them, then re-run).

The script exits with status 1 if either list is non-empty, so it can gate a
release step. Only the standard library is used.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from importlib import metadata
from pathlib import Path

REQ_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def read_requirements(path: Path) -> list[str]:
    names = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        match = REQ_NAME.match(line)
        if match:
            names.append(match.group(1))
    return names


def imported_top_level_modules(code_dir: Path) -> set[str]:
    modules: set[str] = set()
    for path in code_dir.rglob("*.py"):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except (SyntaxError, UnicodeDecodeError) as exc:
            print(f"warning: skipped {path}: {exc}", file=sys.stderr)
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                modules.update(alias.name.split(".")[0] for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                modules.add(node.module.split(".")[0])
    return modules


def local_module_names(code_dir: Path) -> set[str]:
    """Modules and packages defined inside the code tree itself."""
    names = {p.stem for p in code_dir.rglob("*.py")}
    names.update(p.parent.name for p in code_dir.rglob("__init__.py"))
    return names


def main() -> int:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--requirements", type=Path, default=here / "requirements.txt")
    parser.add_argument("--output", type=Path, default=here / "requirements.lock.txt")
    parser.add_argument(
        "--code-dir",
        type=Path,
        help="experiment code to scan for imports missing from requirements.txt",
    )
    args = parser.parse_args()

    listed = read_requirements(args.requirements)
    pinned, not_installed = [], []
    for name in listed:
        try:
            pinned.append(f"{name}=={metadata.version(name)}")
        except metadata.PackageNotFoundError:
            not_installed.append(name)

    header = (
        "# Exact versions from the environment that produced the results.\n"
        f"# Generated by pin_requirements.py with Python {sys.version.split()[0]}.\n"
    )
    args.output.write_text(header + "\n".join(pinned) + "\n", encoding="utf-8")
    print(f"wrote {args.output} ({len(pinned)} packages)")

    unlisted: dict[str, str] = {}
    if args.code_dir:
        listed_norm = {normalize(n) for n in listed}
        module_to_dists = metadata.packages_distributions()
        skip = set(sys.stdlib_module_names) | local_module_names(args.code_dir)
        for module in sorted(imported_top_level_modules(args.code_dir) - skip):
            dists = module_to_dists.get(module)
            if not dists:
                unlisted[module] = "(not installed; unknown distribution)"
            elif not any(normalize(d) in listed_norm for d in dists):
                unlisted[module] = ", ".join(sorted(set(dists)))

    if not_installed:
        print("\nlisted but not installed (remove, or install and re-run):")
        for name in not_installed:
            print(f"  {name}")
    if unlisted:
        print("\nimported by the code but not in requirements.txt (add and re-run):")
        for module, dists in unlisted.items():
            print(f"  import {module}  ->  {dists}")
    if not_installed or unlisted:
        return 1
    print("\nall listed packages are installed and all imports are covered.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
